//! OpenAPI models for the MonaDB control plane.
//!
//! @generated by `cargo run --features generate --bin generate_models`
//! from mona-types/generated/openapi.json. Do not edit by hand.

#![allow(clippy::all)]
#![allow(rustdoc::broken_intra_doc_links)]

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///Request body for creating a database.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Request body for creating a database.",
///  "type": "object",
///  "required": [
///    "name"
///  ],
///  "properties": {
///    "name": {
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateDatabaseRequest {
    pub name: ::std::string::String,
}
impl ::std::convert::From<&CreateDatabaseRequest> for CreateDatabaseRequest {
    fn from(value: &CreateDatabaseRequest) -> Self {
        value.clone()
    }
}
///A provisioned MonaDB logical database.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "A provisioned MonaDB logical database.",
///  "type": "object",
///  "required": [
///    "connectionString",
///    "createdAt",
///    "hostname",
///    "id",
///    "name",
///    "status"
///  ],
///  "properties": {
///    "connectionString": {
///      "description": "MongoDB connection URI including TLS query params for local use.",
///      "type": "string"
///    },
///    "createdAt": {
///      "description": "ISO-8601 creation timestamp.",
///      "type": "string",
///      "format": "date-time"
///    },
///    "hostname": {
///      "description": "SNI hostname for this database.",
///      "type": "string"
///    },
///    "id": {
///      "description": "Stable identifier used in hostnames (e.g. abc123).",
///      "type": "string"
///    },
///    "name": {
///      "description": "Human-readable name.",
///      "type": "string"
///    },
///    "status": {
///      "$ref": "#/definitions/DatabaseStatus"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct Database {
    ///MongoDB connection URI including TLS query params for local use.
    #[serde(rename = "connectionString")]
    pub connection_string: ::std::string::String,
    ///ISO-8601 creation timestamp.
    #[serde(rename = "createdAt")]
    pub created_at: ::chrono::DateTime<::chrono::offset::Utc>,
    ///SNI hostname for this database.
    pub hostname: ::std::string::String,
    ///Stable identifier used in hostnames (e.g. abc123).
    pub id: ::std::string::String,
    ///Human-readable name.
    pub name: ::std::string::String,
    pub status: DatabaseStatus,
}
impl ::std::convert::From<&Database> for Database {
    fn from(value: &Database) -> Self {
        value.clone()
    }
}
///Lifecycle status of a logical database.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Lifecycle status of a logical database.",
///  "type": "string",
///  "enum": [
///    "pending",
///    "ready",
///    "sleeping",
///    "error"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum DatabaseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "sleeping")]
    Sleeping,
    #[serde(rename = "error")]
    Error,
}
impl ::std::convert::From<&Self> for DatabaseStatus {
    fn from(value: &DatabaseStatus) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for DatabaseStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Pending => f.write_str("pending"),
            Self::Ready => f.write_str("ready"),
            Self::Sleeping => f.write_str("sleeping"),
            Self::Error => f.write_str("error"),
        }
    }
}
impl ::std::str::FromStr for DatabaseStatus {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "pending" => Ok(Self::Pending),
            "ready" => Ok(Self::Ready),
            "sleeping" => Ok(Self::Sleeping),
            "error" => Ok(Self::Error),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DatabaseStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for DatabaseStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DatabaseStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Error payload returned for 4xx/5xx responses (`{ detail: string }`).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Error payload returned for 4xx/5xx responses (`{ detail: string }`).",
///  "type": "object",
///  "required": [
///    "detail"
///  ],
///  "properties": {
///    "detail": {
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct ErrorBody {
    pub detail: ::std::string::String,
}
impl ::std::convert::From<&ErrorBody> for ErrorBody {
    fn from(value: &ErrorBody) -> Self {
        value.clone()
    }
}
///Request body for updating a database.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Request body for updating a database.",
///  "type": "object",
///  "required": [
///    "name"
///  ],
///  "properties": {
///    "name": {
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateDatabaseRequest {
    pub name: ::std::string::String,
}
impl ::std::convert::From<&UpdateDatabaseRequest> for UpdateDatabaseRequest {
    fn from(value: &UpdateDatabaseRequest) -> Self {
        value.clone()
    }
}


impl DatabaseStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Ready => "ready",
            Self::Sleeping => "sleeping",
            Self::Error => "error",
        }
    }
}
