import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const openapiPath = join(root, "tsp-output", "@typespec", "openapi3", "openapi.json");
const outDir = join(root, "generated");
const typesFile = join(outDir, "openapi.ts");
const clientFile = join(outDir, "client.ts");

const ast = await openapiTS(new URL(`file://${openapiPath}`));
await mkdir(outDir, { recursive: true });
await writeFile(typesFile, astToString(ast));

const openapi = await readFile(openapiPath, "utf8");
await writeFile(join(outDir, "openapi.json"), openapi);

const clientSource = `/* eslint-disable */
/**
 * This file is auto-generated by scripts/generate-ts.mjs.
 * Do not edit directly.
 */
import createClient from "openapi-fetch";
import type { components, paths } from "./openapi";

export type { components, paths };
export type Database = components["schemas"]["Database"];
export type DatabaseStatus = components["schemas"]["DatabaseStatus"];
export type CreateDatabaseRequest = components["schemas"]["CreateDatabaseRequest"];
export type UpdateDatabaseRequest = components["schemas"]["UpdateDatabaseRequest"];
export type ErrorBody = components["schemas"]["ErrorBody"];

export type MonaClient = ReturnType<typeof createMonaClient>;

export function createMonaClient(baseUrl: string) {
  return createClient<paths>({ baseUrl: baseUrl.replace(/\\/$/, "") });
}
`;

await writeFile(clientFile, clientSource);

console.log(`Wrote ${typesFile}`);
console.log(`Wrote ${clientFile}`);
console.log(`Wrote ${join(outDir, "openapi.json")}`);
