apiVersion: v1
kind: Service
metadata:
  name: ${K8S_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: mona-db
    app.kubernetes.io/instance: ${K8S_NAME}
    mona.db/id: ${DB_ID}
spec:
  selector:
    app.kubernetes.io/instance: ${K8S_NAME}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
